"""Company knowledge base for the Crystal Arc lead-reactivation analysis.

Each entry: core_key -> (tier, parent_group, group_status, industry, company_type, evidence, source, research_status)
  tier: A Major / B Strong / C Good potential / D Small / E Needs verification / F Not suitable
  research_status: "Web-verified" (checked via live web search during this analysis),
                   "Desk-verified" (well-known public entity; official site listed as source),
                   "Needs Verification" (identity or scale ambiguous)
Keys are "core" names produced by analyze.core_key() (lower case, legal suffixes and generic words removed).
"""

WV, DV, NV = "Web-verified", "Desk-verified", "Needs Verification"

KB = {
    # ---------------- Hospitality ----------------
    "mandarin oriental hotel": ("A", "Mandarin Oriental Hotel Group (Jardine Matheson)", "Confirmed", "Hospitality / Hotels", "Multinational", "Global luxury hotel group; operates Emirates Palace Abu Dhabi & Mandarin Oriental Jumeira", "mandarinoriental.com", DV),
    "emirates palace": ("A", "Mandarin Oriental Hotel Group (operator)", "Confirmed", "Hospitality / Hotels", "Major UAE brand", "Iconic Abu Dhabi palace hotel; contact used @mohg.com (Mandarin Oriental) email", "mandarinoriental.com/abu-dhabi", DV),
    "accor": ("A", "Accor", "Confirmed", "Hospitality / Hotels", "Multinational", "Global hotel group (Novotel, Sofitel, Fairmont, Raffles); @accor.com email", "group.accor.com", DV),
    "novotel dhahran hotel and residences": ("A", "Accor", "Confirmed", "Hospitality / Hotels", "Multinational", "Accor-branded hotel in KSA; @accor.com email", "group.accor.com", DV),
    "conrad": ("A", "Hilton", "Confirmed", "Hospitality / Hotels", "Multinational", "Conrad is a Hilton luxury brand", "hilton.com", DV),
    "double tree by hilton": ("B", "Hilton", "Confirmed", "Hospitality / Hotels", "Multinational", "DoubleTree is a Hilton brand (single property enquiry)", "hilton.com", DV),
    "hyatt hotel": ("A", "Hyatt Hotels Corporation", "Confirmed", "Hospitality / Hotels", "Multinational", "@hyatt.com email; global hotel group", "hyatt.com", DV),
    "hyaat": ("E", "Possibly Hyatt (spelling)", "Unconfirmed", "Hospitality / Hotels", "Unclear", "Marked Big Name but spelled 'Hyaat', no email - could be Hyatt or a different company", "", NV),
    "kempinski hotels": ("A", "Kempinski", "Confirmed", "Hospitality / Hotels", "Multinational", "European luxury hotel group with several UAE/GCC properties", "kempinski.com", DV),
    "one and only": ("A", "Kerzner International", "Confirmed", "Hospitality / Hotels", "Multinational", "Ultra-luxury resort brand (One&Only Royal Mirage, One&Only One Za'abeel)", "oneandonlyresorts.com", DV),
    "one and only royal mirage": ("A", "Kerzner International", "Confirmed", "Hospitality / Hotels", "Multinational", "One&Only Royal Mirage Dubai", "oneandonlyresorts.com", DV),
    "shangrila": ("A", "Shangri-La Group", "Confirmed", "Hospitality / Hotels", "Multinational", "@shangri-la.com email; global hotel group", "shangri-la.com", DV),
    "ritz carlton hotel difc": ("A", "Marriott International", "Confirmed", "Hospitality / Hotels", "Multinational", "Ritz-Carlton is a Marriott luxury brand", "marriott.com", DV),
    "rove": ("B", "Emaar / Meraas (Rove Hotels)", "Probable", "Hospitality / Hotels", "Major UAE brand", "If Rove Hotels: Emaar-Meraas JV hotel chain; name only - confirm", "rovehotels.com", NV),
    "palazzo tbilisi": ("E", "", "Unknown", "Hospitality / Hotels", "Unclear", "Marked Big Name; no public evidence of scale found in data", "", NV),
    "emirates park": ("C", "", "Unknown", "Tourism", "Local established", "Marked BIG NAME - Emirates Park Zoo & Resort (Abu Dhabi), mid-size leisure venue", "emiratespark.ae", DV),
    "uld": ("E", "Possibly Trafalgar Luxury Group", "Unconfirmed", "Other", "Unclear", "Marked Big name; email @trafalgarluxurygroup.com - verify group scale", "trafalgarluxurygroup.com", NV),
    "best places to work": ("C", "Best Places to Work (certification programme)", "Probable", "Professional Services", "Trade buyer", "Marked Decent Name - workplace certification organiser; buys awards for certified companies (recurring)", "", NV),
    "media one hotel": ("C", "", "Unknown", "Hospitality / Hotels", "Local established", "Dubai Media City 4-star hotel", "mediaonehotel.com", DV),
    "o beach": ("C", "", "Unknown", "Hospitality / Hotels", "Local established", "Beach club venue in Dubai", "obeachdubai.com", DV),
    # ---------------- Government / semi-government ----------------
    "abu dhabi accountability authority": ("A", "Government of Abu Dhabi", "Confirmed", "Government", "Government", "@adaa.gov.ae; Abu Dhabi government audit authority", "adaa.gov.ae", DV),
    "adu dhabi executive office": ("A", "Government of Abu Dhabi", "Confirmed", "Government", "Government", "Abu Dhabi Executive Office (name typo in source)", "executiveoffice.gov.ae", DV),
    "executive office of his highness sheikh mohammed bin rashid al maktoum": ("A", "Government of Dubai", "Confirmed", "Government", "Government", "@teo.ae; The Executive Office of HH Sheikh Mohammed", "teo.ae", DV),
    "executive affairs authority": ("A", "Government of Abu Dhabi", "Confirmed", "Government", "Government", "Abu Dhabi Executive Affairs Authority", "", DV),
    "abu dhabi heritage authority": ("A", "Government of Abu Dhabi", "Confirmed", "Government", "Government", "Government heritage authority", "", DV),
    "abu dhabi sports council": ("A", "Government of Abu Dhabi", "Confirmed", "Sports", "Government", "Government sports regulator - runs many events/tournaments", "adsc.gov.ae", DV),
    "dubai sports council": ("A", "Government of Dubai", "Confirmed", "Sports", "Government", "Government sports regulator - many championships annually", "dubaisc.ae", DV),
    "dubai municipality": ("A", "Government of Dubai", "Confirmed", "Government", "Government", "Dubai Municipality", "dm.gov.ae", DV),
    "rta": ("A", "Government of Dubai", "Confirmed", "Government", "Government", "Roads & Transport Authority Dubai", "rta.ae", DV),
    "department of energy": ("A", "Government of Abu Dhabi", "Probable", "Government", "Government", "Likely Abu Dhabi Department of Energy (marked Big Name)", "doe.gov.ae", DV),
    "creative media authority auh": ("A", "Government of Abu Dhabi", "Confirmed", "Government", "Government", "@cma.gov.ae", "cma.gov.ae", DV),
    "federal demographic council": ("A", "UAE Federal Government", "Confirmed", "Government", "Government", "@fdc.gov.ae; bespoke gifts enquiry in progress", "fdc.gov.ae", DV),
    "tawazun council for defence enablement": ("A", "UAE Federal Government", "Confirmed", "Government", "Government", "@tawazun.gov.ae defence procurement council", "tawazun.gov.ae", DV),
    "tawazun": ("A", "UAE Federal Government", "Confirmed", "Government", "Government", "@tawazun.gov.ae", "tawazun.gov.ae", DV),
    "tawazun industrial park tip": ("B", "Tawazun Council", "Confirmed", "Government", "Semi-Government", "@tip.ae; industrial park under Tawazun", "tip.ae", DV),
    "ministry of industry and advanced technology": ("A", "UAE Federal Government", "Confirmed", "Government", "Government", "UAE MoIAT (federal ministry)", "moiat.gov.ae", DV),
    "undersecretary of the ministry of industry and advanced technology": ("A", "UAE Federal Government", "Confirmed", "Government", "Government", "Office of the Undersecretary, MoIAT", "moiat.gov.ae", DV),
    "ministry of affairs saudi": ("B", "Government of Saudi Arabia", "Unconfirmed", "Government", "Government", "Saudi ministry - exact ministry not recorded; order was won", "", NV),
    "dubai center for economic security": ("B", "Government of Dubai", "Confirmed", "Government", "Government", "Dubai government centre", "", DV),
    "knowledge fund establishment gov": ("B", "Government of Dubai", "Confirmed", "Government", "Government", "Dubai Knowledge Fund Establishment", "", DV),
    "investment arm of the asir municipality": ("B", "Asir Municipality (KSA)", "Confirmed", "Government", "Semi-Government", "Municipal investment arm, KSA", "", DV),
    "sharjah commerce and tourism development authority": ("A", "Government of Sharjah", "Confirmed", "Government", "Government", "@sharjahtourism.ae; 2 enquiries", "sharjahtourism.ae", DV),
    "sharjah government": ("A", "Government of Sharjah", "Probable", "Government", "Government", "Department not recorded - order won", "", NV),
    "ektifa": ("B", "Government of Sharjah (Dept. of Agriculture & Livestock)", "Confirmed", "Government", "Semi-Government", "Sharjah Agriculture & Livestock Production Est. - government-owned; 3 won orders", "ektifa.ae", WV),
    "uae naval forces command": ("A", "UAE Armed Forces", "Confirmed", "Government", "Government", "UAE Naval Forces", "", DV),
    "us army": ("B", "US Government", "Unconfirmed", "Government", "Government", "Foreign military - confirm legitimacy & buying entity", "", NV),
    "creative media authority": ("A", "Government of Abu Dhabi", "Confirmed", "Government", "Government", "Abu Dhabi Creative Media Authority", "cma.gov.ae", DV),
    "philippine consulate general": ("B", "Government of the Philippines", "Confirmed", "Government", "Diplomatic", "@pcgdubai.ae; order won", "pcgdubai.ae", DV),
    "consulate general of the kingdom of morocco in": ("B", "Government of Morocco", "Confirmed", "Government", "Diplomatic", "Consulate in Dubai; order won", "", DV),
    "hong kong economic and trade office in": ("B", "HKSAR Government", "Confirmed", "Government", "Diplomatic", "HKETO Dubai", "hketodubai.gov.hk", DV),
    "future health a global initiative by abu dhabi": ("B", "Department of Health Abu Dhabi", "Probable", "Government", "Government", "Abu Dhabi DoH initiative; order won", "", DV),
    "riyadh second health cluster": ("A", "Saudi Ministry of Health", "Confirmed", "Healthcare", "Government", "Saudi MoH health cluster; order won", "", DV),
    "saudi port authority": ("A", "Government of Saudi Arabia (Mawani)", "Confirmed", "Government", "Government", "Saudi Ports Authority", "mawani.gov.sa", DV),
    "saqr port": ("B", "RAK Ports (Government of Ras Al Khaimah)", "Confirmed", "Logistics / Shipping / Aviation", "Semi-Government", "Saqr Port is a RAK Ports facility (contact used gmail)", "rakports.ae", DV),
    "shams free zone": ("B", "Government of Sharjah", "Confirmed", "Government", "Semi-Government", "Sharjah Media City free zone", "shams.ae", DV),
    "ras al khaimah economic zone": ("A", "Government of Ras Al Khaimah", "Confirmed", "Government", "Semi-Government", "@rakez.com; major free zone; order won", "rakez.com", DV),
    "dmcc": ("A", "Government of Dubai", "Confirmed", "Government", "Semi-Government", "Dubai Multi Commodities Centre free zone", "dmcc.ae", DV),
    "difc courts": ("A", "Government of Dubai (DIFC)", "Confirmed", "Government", "Government", "DIFC Courts", "difccourts.ae", DV),
    "adgm academy": ("A", "Abu Dhabi Global Market", "Confirmed", "Government", "Semi-Government", "@adgm.com; ADGM financial free zone academy", "adgm.com", DV),
    "modon": ("A", "MODON (Saudi Authority for Industrial Cities) / Modon Holding AD", "Unconfirmed", "Government", "Semi-Government", "Two possible MODONs (KSA authority or Abu Dhabi Modon Holding) - both major", "", NV),
    "world free zones organization": ("B", "", "Unknown", "Associations / Non-profit", "International body", "Dubai-headquartered international free zone association", "worldfzo.org", DV),
    "sharjah broadcasting advertising": ("B", "Sharjah Broadcasting Authority", "Probable", "Media", "Semi-Government", "Sharjah government broadcaster; order won", "sba.gov.ae", DV),
    # ---------------- Ports / logistics / aviation ----------------
    "ad ports": ("A", "AD Ports Group (ADQ)", "Confirmed", "Logistics / Shipping / Aviation", "Semi-Government", "Listed Abu Dhabi ports group", "adportsgroup.com", DV),
    "abu dhabi terminal": ("B", "AD Ports Group (probable)", "Probable", "Logistics / Shipping / Aviation", "Semi-Government", "Abu Dhabi Terminals - Khalifa Port operator", "adportsgroup.com", DV),
    "dp world": ("A", "DP World (Dubai World)", "Confirmed", "Logistics / Shipping / Aviation", "Major UAE brand", "Global ports operator; 3 enquiries incl. won order", "dpworld.com", DV),
    "dubai maritime city": ("B", "Government of Dubai", "Probable", "Logistics / Shipping / Aviation", "Semi-Government", "@dubaimaritimecity.ae", "dubaimaritimecity.ae", DV),
    "maersk shipping line": ("A", "A.P. Moller - Maersk", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "Global shipping line; order won", "maersk.com", DV),
    "cma cgm": ("A", "CMA CGM Group", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "Global shipping line", "cma-cgm.com", DV),
    "hapaglloyd shipping": ("A", "Hapag-Lloyd", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "@hlag.com", "hapag-lloyd.com", DV),
    "hellmann worldwide logistics": ("A", "Hellmann", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "Global logistics group", "hellmann.com", DV),
    "dhl": ("A", "Deutsche Post DHL", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "@dhl.com", "dhl.com", DV),
    "expeditors": ("A", "Expeditors International", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "NYSE-listed logistics", "expeditors.com", DV),
    "svitzer": ("B", "Svitzer", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "Global towage company; order won", "svitzer.com", DV),
    "dnata airport operations": ("A", "Emirates Group", "Confirmed", "Logistics / Shipping / Aviation", "Major UAE brand", "dnata is part of Emirates Group", "dnata.com", DV),
    "emirates airlines": ("A", "Emirates Group", "Confirmed", "Logistics / Shipping / Aviation", "Major UAE brand", "Emirates airline", "emirates.com", DV),
    "emirates": ("E", "Possibly Emirates Group", "Unconfirmed", "Logistics / Shipping / Aviation", "Unclear", "Recorded only as 'Emirates' - verify which entity", "", NV),
    "ethiopian airlines": ("A", "Ethiopian Airlines Group", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "National carrier with Dubai office", "ethiopianairlines.com", DV),
    "turkish airlines": ("A", "Turkish Airlines", "Confirmed", "Logistics / Shipping / Aviation", "Multinational", "National carrier", "turkishairlines.com", DV),
    "transguard": ("A", "Emirates Group", "Confirmed", "Professional Services", "Major UAE brand", "@transguardgroup.com; Emirates Group outsourcing company", "transguardgroup.com", DV),
    "sami airbus aircraft maintenance": ("A", "SAMI (Saudi Arabian Military Industries, PIF)", "Probable", "Logistics / Shipping / Aviation", "Semi-Government", "SAMI is PIF-owned defence company; order won", "sami.com.sa", DV),
    "rightjet": ("E", "", "Unknown", "Logistics / Shipping / Aviation", "Unclear", "Marked BIG NAME; private aviation brand - scale not evidenced", "", NV),
    "fujairah aviation academy": ("C", "Fujairah National Group", "Probable", "Education", "Local established", "@fng.ae - part of Fujairah National Group", "fng.ae", DV),
    "fujairah national": ("B", "Fujairah National Group", "Confirmed", "Other / Conglomerate", "Major local group", "Fujairah-based diversified group", "fng.ae", DV),
    "mercantile and maritime": ("B", "Unclear: MMI (Emirates Group) or Mercantile & Maritime Group (energy trading)", "Unconfirmed", "Energy / Oil & Gas", "Unclear", "Two large companies share this name - confirm which; order won", "", WV),
    # ---------------- Real estate / construction ----------------
    "emaar": ("A", "Emaar Properties", "Confirmed", "Real Estate", "Major UAE brand", "Largest UAE listed developer", "emaar.com", DV),
    "dubai holdings real estate": ("A", "Dubai Holding", "Confirmed", "Real Estate", "Major UAE brand", "Dubai Holding real estate arm; order won", "dubaiholding.com", DV),
    "dubai holding": ("A", "Dubai Holding", "Confirmed", "Other / Conglomerate", "Major UAE brand", "@dhgroupservices.com; Dubai government-owned conglomerate", "dubaiholding.com", DV),
    "wasl property management": ("A", "wasl (Dubai Holding)", "Confirmed", "Real Estate", "Semi-Government", "@wasl.ae; one of Dubai's largest landlords", "wasl.ae", DV),
    "azizi development": ("A", "Azizi Group", "Confirmed", "Real Estate", "Major UAE brand", "Major Dubai developer; 2 enquiries", "azizidevelopments.com", DV),
    "azizi developments": ("A", "Azizi Group", "Confirmed", "Real Estate", "Major UAE brand", "Major Dubai developer", "azizidevelopments.com", DV),
    "samana": ("B", "SAMANA Group of Companies", "Confirmed", "Real Estate", "Major local group", "SAMANA Developers - 30+ Dubai projects; group since 1996 (contact used italtechcontracting.com - a group firm)", "samanadevelopers.com", WV),
    "danube properties": ("B", "Danube Group", "Confirmed", "Real Estate", "Major local group", "Major Dubai developer (Danube Group)", "danubeproperties.ae", DV),
    "ellington properties development": ("B", "", "Unknown", "Real Estate", "Local established", "Established premium Dubai developer", "ellingtonproperties.ae", DV),
    "ora developers": ("B", "Ora Developers (Naguib Sawiris)", "Confirmed", "Real Estate", "Regional", "Regional developer", "oradevelopers.com", DV),
    "arada developers": ("B", "Arada", "Confirmed", "Real Estate", "Major local group", "Sharjah master developer (Aljada, Masaar)", "arada.com", DV),
    "fakhruddin properties development": ("B", "Fakhruddin Holdings", "Confirmed", "Real Estate", "Local established", "@fakhruddinproperties.com", "fakhruddinproperties.com", DV),
    "jubail island investment": ("B", "Abu Dhabi govt-linked (LUNATE / ADQ-linked developer)", "Probable", "Real Estate", "Semi-Government", "Master developer of Jubail Island AD; 2 enquiries", "jubailisland.ae", DV),
    "ohana": ("B", "Ohana Development", "Confirmed", "Real Estate", "Major local group", "Abu Dhabi luxury developer, 2,000+ staff, USD 8bn+ assets (email odgt.ae)", "ohana.ae", WV),
    "pif real estate": ("A", "Public Investment Fund (KSA)", "Probable", "Real Estate", "Semi-Government", "PIF real estate subsidiary", "pif.gov.sa", DV),
    "al barari": ("B", "", "Unknown", "Real Estate", "Local established", "Established Dubai luxury community developer", "albarari.com", DV),
    "al hamra real estate": ("B", "Al Hamra Group (RAK)", "Probable", "Real Estate", "Local established", "RAK developer - contact used gmail; 'not our scope'", "alhamra.ae", DV),
    "driven properties": ("C", "", "Unknown", "Real Estate", "Local established", "Large Dubai brokerage", "drivenproperties.com", DV),
    "remax": ("B", "RE/MAX (franchise)", "Confirmed", "Real Estate", "Multinational franchise", "International brokerage franchise", "remax-uae.com", DV),
    "engel and voelkers": ("B", "Engel & Völkers", "Confirmed", "Real Estate", "Multinational franchise", "@engelvoelkers.com; 2 enquiries", "engelvoelkers.com", DV),
    "bayut and dubbizle": ("A", "Dubizzle Group", "Confirmed", "Technology", "Major UAE brand", "UAE's largest property/classifieds platforms", "dubizzlegroup.com", DV),
    "alec": ("A", "ALEC Holdings (ICD)", "Confirmed", "Construction / Engineering", "Major UAE brand", "Major UAE contractor owned by Investment Corporation of Dubai", "alec.ae", DV),
    "alec holding": ("A", "ALEC Holdings (ICD)", "Confirmed", "Construction / Engineering", "Major UAE brand", "Padel trophies enquiry", "alec.ae", DV),
    "nmdc": ("A", "NMDC Group (Alpha Dhabi)", "Confirmed", "Construction / Engineering", "Major UAE brand", "@nmdc-group.com; listed marine dredging & EPC group", "nmdc-group.com", DV),
    "naffco": ("A", "NAFFCO", "Confirmed", "Manufacturing / Industrial", "Major UAE brand", "Major UAE fire-safety manufacturer, global exports", "naffco.com", DV),
    "trojan": ("B", "Trojan Construction Group (IHC / Alpha Dhabi)", "Probable", "Construction / Engineering", "Major local group", "Large Abu Dhabi contractor", "trojan.ae", DV),
    "wade adams contracting": ("B", "", "Unknown", "Construction / Engineering", "Local established", "Established UAE contractor", "wadeadams.com", DV),
    "unibeton ready mix": ("B", "", "Unknown", "Construction / Engineering", "Local established", "Large UAE ready-mix supplier", "unibeton.ae", DV),
    "standard carpets ind": ("B", "", "Unknown", "Manufacturing / Industrial", "Local established", "Long-established UAE carpet manufacturer", "standardcarpets.com", DV),
    "schindler elevators and escalators": ("A", "Schindler Group", "Confirmed", "Construction / Engineering", "Multinational", "Global elevator manufacturer", "schindler.com", DV),
    "layher": ("B", "Layher", "Confirmed", "Construction / Engineering", "Multinational", "@layher.com; German scaffolding manufacturer", "layher.com", DV),
    "applus": ("B", "Applus+", "Confirmed", "Professional Services", "Multinational", "@applus.com; testing & inspection", "applus.com", DV),
    "sgs gulf": ("A", "SGS", "Confirmed", "Professional Services", "Multinational", "Global inspection/certification", "sgs.com", DV),
    "bsi": ("B", "BSI Group", "Confirmed", "Professional Services", "Multinational", "@bsigroup.com; standards body", "bsigroup.com", DV),
    "galadari trucks and heavy equipment": ("B", "Galadari Brothers Group", "Confirmed", "Automotive", "Major local group", "@galadaribrothers.com; 2 enquiries", "galadaribrothers.com", DV),
    "emirates specialized contracting and oilfield services": ("B", "", "Unknown", "Energy / Oil & Gas", "Local established", "Abu Dhabi oilfield contractor (ESCO)", "", DV),
    # ---------------- Energy ----------------
    "china petroleum": ("A", "CNPC / China Petroleum group (entity to confirm)", "Unconfirmed", "Energy / Oil & Gas", "Multinational", "Chinese state oil group entity - order won; confirm exact subsidiary", "", NV),
    "siemens energy": ("A", "Siemens Energy", "Confirmed", "Energy / Oil & Gas", "Multinational", "Global energy technology", "siemens-energy.com", DV),
    "ge vernova": ("A", "GE Vernova", "Confirmed", "Energy / Oil & Gas", "Multinational", "Global energy company (GE spin-off)", "gevernova.com", DV),
    "general electric vernova": ("A", "GE Vernova", "Confirmed", "Energy / Oil & Gas", "Multinational", "@ge.com", "gevernova.com", DV),
    "national energy services reunited corp nesr": ("B", "NESR", "Confirmed", "Energy / Oil & Gas", "Regional", "@nesr.com; Nasdaq-listed MENA oilfield services", "nesr.com", DV),
    "precision drilling": ("B", "Precision Drilling Corp", "Confirmed", "Energy / Oil & Gas", "Multinational", "@precisiondrilling.com; NYSE/TSX listed; order won", "precisiondrilling.com", DV),
    "jereh oil and gas": ("B", "Jereh Group", "Confirmed", "Energy / Oil & Gas", "Multinational", "Chinese listed oilfield equipment group", "jereh.com", DV),
    "united energy": ("B", "United Energy Group", "Confirmed", "Energy / Oil & Gas", "Multinational", "HK-listed E&P group; ADIPEC gifts enquiry", "uegl.com.hk", DV),
    "texol lubritech": ("B", "Gandhar Oil Refinery (India) JV", "Confirmed", "Energy / Oil & Gas", "Local established", "Lubricant manufacturer, Hamriyah FZ, 200k MT plant; marked BIG NAME", "texollubritech.com", WV),
    "yellow door energy": ("B", "", "Unknown", "Energy / Oil & Gas", "Regional", "Regional solar developer", "yellowdoorenergy.com", DV),
    "nomac": ("B", "ACWA Power", "Confirmed", "Energy / Oil & Gas", "Regional", "O&M arm of ACWA Power", "nomac.com", DV),
    "enoc station 1056": ("C", "ENOC", "Confirmed", "Energy / Oil & Gas", "Branch of major group", "Single fuel-station enquiry - ENOC is major but decision-maker is station level", "enoc.com", DV),
    "advanced petro services": ("C", "", "Unknown", "Energy / Oil & Gas", "Local established", "@apsenergy.com; marked big name but scale not evidenced", "apsenergy.com", NV),
    # ---------------- Corporate multinationals ----------------
    "adidas": ("A", "adidas AG", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "Global sportswear brand; order won", "adidas.com", DV),
    "amazon": ("A", "Amazon", "Confirmed", "Technology", "Multinational", "3 enquiries incl. won order", "amazon.ae", DV),
    "american express": ("A", "American Express", "Confirmed", "Banking / Finance / Insurance", "Multinational", "", "americanexpress.com", DV),
    "asus": ("A", "ASUS", "Confirmed", "Technology", "Multinational", "", "asus.com", DV),
    "byd": ("A", "BYD", "Confirmed", "Automotive", "Multinational", "Global EV maker", "byd.com", DV),
    "cartier": ("A", "Richemont", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "@cartier.com; order won", "cartier.com", DV),
    "compass": ("A", "Compass Group", "Confirmed", "Hospitality / Hotels", "Multinational", "Global food-service; order won", "compass-group.com", DV),
    "ecolab": ("A", "Ecolab", "Confirmed", "Manufacturing / Industrial", "Multinational", "2 enquiries (crystal trophy, falcon trophy)", "ecolab.com", DV),
    "essilorluxottica": ("A", "EssilorLuxottica", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "Order won", "essilorluxottica.com", DV),
    "flir systems dwc": ("A", "Teledyne FLIR", "Confirmed", "Technology", "Multinational", "Order won", "flir.com", DV),
    "ge healthcare": ("A", "GE HealthCare", "Confirmed", "Healthcare", "Multinational", "@gehealthcare.com; order won", "gehealthcare.com", DV),
    "georgfisher": ("A", "Georg Fischer", "Confirmed", "Manufacturing / Industrial", "Multinational", "@georgfischer.com", "georgfischer.com", DV),
    "gmr": ("A", "GMR Group", "Confirmed", "Construction / Engineering", "Multinational", "Indian infrastructure conglomerate", "gmrgroup.in", DV),
    "huda beauty": ("A", "Huda Beauty", "Confirmed", "Retail / Consumer / Luxury", "Major UAE brand", "Global beauty brand HQ Dubai", "hudabeauty.com", DV),
    "indra": ("A", "Indra Sistemas", "Confirmed", "Technology", "Multinational", "@indracompany.com", "indracompany.com", DV),
    "jcb": ("A", "JCB", "Confirmed", "Automotive", "Multinational", "Won orders from JCB entities", "jcb.com", DV),
    "jcb construction equipment": ("A", "JCB", "Confirmed", "Automotive", "Multinational", "Order won", "jcb.com", DV),
    "karcher jafza": ("A", "Kärcher", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "kaercher.com", DV),
    "lexisnexis risk solutions": ("A", "RELX", "Confirmed", "Technology", "Multinational", "", "risk.lexisnexis.com", DV),
    "lucid motors": ("A", "Lucid Group (PIF-backed)", "Confirmed", "Automotive", "Multinational", "Order won (cup & medals)", "lucidmotors.com", DV),
    "m h i": ("A", "Mitsubishi Heavy Industries", "Confirmed", "Manufacturing / Industrial", "Multinational", "@mhi.com", "mhi.com", DV),
    "marubeni itochu tubulars": ("A", "Marubeni-Itochu Steel", "Confirmed", "Manufacturing / Industrial", "Multinational", "Japanese trading-house JV", "", DV),
    "netapp": ("A", "NetApp", "Confirmed", "Technology", "Multinational", "@netapp.com", "netapp.com", DV),
    "oracle": ("A", "Oracle", "Confirmed", "Technology", "Multinational", "", "oracle.com", DV),
    "red bull": ("A", "Red Bull", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "Order won", "redbull.com", DV),
    "sany": ("A", "SANY Group", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "sanyglobal.com", DV),
    "savola foods": ("A", "Savola Group", "Confirmed", "Retail / Consumer / Luxury", "Regional", "@savola.com; Saudi listed food group", "savola.com", DV),
    "schneider electric": ("A", "Schneider Electric", "Confirmed", "Manufacturing / Industrial", "Multinational", "@se.com; in progress", "se.com", DV),
    "thermo fisher": ("A", "Thermo Fisher Scientific", "Confirmed", "Healthcare", "Multinational", "@thermofisher.com", "thermofisher.com", DV),
    "thoshiba": ("A", "Toshiba (probable)", "Probable", "Technology", "Multinational", "Spelled 'Thoshiba' - name add-on to existing trophy", "toshiba.com", NV),
    "wendys": ("A", "Wendy's", "Confirmed", "Food & Beverage", "Multinational", "@wendys.com; in progress", "wendys.com", DV),
    "yamaha motors": ("A", "Yamaha Motor", "Confirmed", "Automotive", "Multinational", "@yamaha-motor.co.jp; order won", "yamaha-motor.com", DV),
    "yokogawa industry": ("A", "Yokogawa Electric", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "yokogawa.com", DV),
    "zte corporation": ("A", "ZTE", "Confirmed", "Technology", "Multinational", "", "zte.com.cn", DV),
    "storck": ("B", "August Storck KG", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "German confectionery group", "storck.com", DV),
    "sobi": ("A", "Swedish Orphan Biovitrum (Sobi)", "Confirmed", "Healthcare", "Multinational", "Listed biopharma in 30+ countries; Dubai regional office; 2 won orders", "sobi.com", WV),
    "ansell": ("B", "Ansell", "Confirmed", "Healthcare", "Multinational", "ASX-listed protective products", "ansell.com", DV),
    "vygon": ("B", "Vygon", "Confirmed", "Healthcare", "Multinational", "French medical devices", "vygon.com", DV),
    "zo skin health": ("B", "ZO Skin Health", "Confirmed", "Healthcare", "Multinational", "Order won", "zoskinhealth.com", DV),
    "himalaya wellness": ("B", "Himalaya Wellness", "Confirmed", "Healthcare", "Multinational", "", "himalayawellness.com", DV),
    "dabur": ("B", "Dabur India", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "", "dabur.com", DV),
    "technogym": ("B", "Technogym", "Confirmed", "Sports", "Multinational", "Order won", "technogym.com", DV),
    "kyb": ("B", "KYB Corporation", "Probable", "Automotive", "Multinational", "", "kyb.co.jp", DV),
    "castolim eutectic": ("B", "Castolin Eutectic", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "castolin.com", DV),
    "dillinger": ("B", "Dillinger (SHS group)", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "dillinger.de", DV),
    "ebara pumps": ("B", "Ebara Corporation", "Confirmed", "Manufacturing / Industrial", "Multinational", "Marked Big Name - regional subsidiary of Japanese listed group", "ebara.com", DV),
    "palfinger marinedubai": ("B", "Palfinger", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "palfinger.com", DV),
    "lisega se": ("B", "LISEGA", "Confirmed", "Manufacturing / Industrial", "Multinational", "", "lisega.de", DV),
    "vitronic machine vision": ("C", "VITRONIC", "Confirmed", "Technology", "Multinational", "@vitronic.com", "vitronic.com", DV),
    "siderise": ("B", "Siderise", "Confirmed", "Manufacturing / Industrial", "Multinational", "Order won", "siderise.com", DV),
    "sauter": ("B", "Sauter", "Probable", "Manufacturing / Industrial", "Multinational", "", "sauter-controls.com", DV),
    "orbcomm": ("B", "ORBCOMM", "Confirmed", "Technology", "Multinational", "", "orbcomm.com", DV),
    "infiled": ("B", "INFiLED", "Confirmed", "Technology", "Multinational", "", "infiled.com", DV),
    "uvex": ("B", "UVEX", "Confirmed", "Manufacturing / Industrial", "Multinational", "@uvex.co.za", "uvex.de", DV),
    "strainstall": ("B", "James Fisher & Sons", "Confirmed", "Construction / Engineering", "Multinational", "", "strainstall.com", DV),
    "saf holland": ("B", "SAF-HOLLAND", "Confirmed", "Automotive", "Multinational", "", "safholland.com", DV),
    "qvest": ("B", "Qvest", "Confirmed", "Technology", "Multinational", "@qvest.com", "qvest.com", DV),
    "troon": ("B", "Troon", "Confirmed", "Sports", "Multinational", "@troon.com; golf management", "troon.com", DV),
    "mahindra emirates vehicle armouring": ("B", "Mahindra Group", "Confirmed", "Automotive", "Multinational", "Marked Big name", "mahindra.com", DV),
    "honda motorcycles jordan": ("C", "Honda (distributor)", "Probable", "Automotive", "Distributor", "@hondajordan.com - Jordan distributor; marked big name", "hondajordan.com", DV),
    "inkas armored": ("B", "INKAS", "Confirmed", "Automotive", "Multinational", "", "inkas.ca", DV),
    "kanoo machinery": ("B", "Yusuf Bin Ahmed Kanoo Group", "Confirmed", "Automotive", "Major local group", "", "kanoomachinery.com", DV),
    "bms masaood": ("B", "Al Masaood Group", "Confirmed", "Other / Conglomerate", "Major local group", "@bmsmasaood.com", "masaood.com", DV),
    # ---------------- Professional services ----------------
    "ey consulting": ("A", "EY", "Confirmed", "Professional Services", "Multinational", "", "ey.com", DV),
    "pwc downtown": ("A", "PwC", "Confirmed", "Professional Services", "Multinational", "Order won", "pwc.com", DV),
    "mckinsey": ("A", "McKinsey & Company", "Confirmed", "Professional Services", "Multinational", "", "mckinsey.com", DV),
    "fti consulting": ("A", "FTI Consulting", "Confirmed", "Professional Services", "Multinational", "Order won", "fticonsulting.com", DV),
    "alixpartners": ("A", "AlixPartners", "Confirmed", "Professional Services", "Multinational", "2 enquiries (one in progress)", "alixpartners.com", DV),
    "white and case llp": ("A", "White & Case", "Confirmed", "Professional Services", "Multinational", "@whitecase.com", "whitecase.com", DV),
    "gibson dunn": ("A", "Gibson Dunn", "Confirmed", "Professional Services", "Multinational", "@gibsondunn.com", "gibsondunn.com", DV),
    "king spalding": ("A", "King & Spalding", "Confirmed", "Professional Services", "Multinational", "", "kslaw.com", DV),
    "fragomen": ("A", "Fragomen", "Confirmed", "Professional Services", "Multinational", "@fragomen.com; order won", "fragomen.com", DV),
    "frago men": ("A", "Fragomen", "Confirmed", "Professional Services", "Multinational", "@fragomen.com; order won", "fragomen.com", DV),
    "gateley": ("B", "Gateley plc", "Confirmed", "Professional Services", "Multinational", "UK-listed law firm; order won", "gateleyplc.com", DV),
    "rsm": ("B", "RSM International", "Confirmed", "Professional Services", "Multinational", "", "rsm.global", DV),
    "linesight": ("B", "Linesight", "Confirmed", "Professional Services", "Multinational", "", "linesight.com", DV),
    "bcd travel": ("B", "BCD Group", "Confirmed", "Professional Services", "Multinational", "@bcdtravel.ae; 2 enquiries (service awards)", "bcdtravel.com", DV),
    "richard attias and associates": ("B", "Richard Attias & Associates", "Confirmed", "Events & Exhibitions", "Multinational", "Global events agency (FII organiser)", "richardattiasassociates.com", DV),
    "george p johnson": ("B", "Project Worldwide", "Confirmed", "Events & Exhibitions", "Multinational", "@gpj.com; global experiential agency", "gpj.com", DV),
    "donedusted": ("B", "Done+Dusted", "Confirmed", "Events & Exhibitions", "Multinational", "Global live-events producer", "doneanddusted.com", DV),
    "messe frankfurt": ("A", "Messe Frankfurt", "Confirmed", "Events & Exhibitions", "Multinational", "Global exhibition organiser; order won", "messefrankfurt.com", DV),
    "ethara": ("B", "", "Unknown", "Events & Exhibitions", "Major local group", "@ethara.com; Abu Dhabi major events operator (Yas Marina Circuit/Etihad Arena)", "ethara.com", DV),
    "impact bbdo": ("B", "Omnicom (BBDO)", "Confirmed", "Advertising / Marketing", "Multinational", "@impactbbdo.com; collaboration enquiry", "impactbbdo.com", DV),
    "innocean": ("B", "Hyundai Motor Group", "Confirmed", "Advertising / Marketing", "Multinational", "@innocean.ae", "innocean.com", DV),
    "mediapro": ("B", "MEDIAPRO", "Probable", "Media", "Multinational", "", "mediapro.tv", DV),
    # ---------------- Banking / finance ----------------
    "abu dhabi islamic bank": ("A", "ADIB", "Confirmed", "Banking / Finance / Insurance", "Major UAE brand", "Padel racket trophies", "adib.ae", DV),
    "efghermes": ("A", "EFG Holding", "Confirmed", "Banking / Finance / Insurance", "Regional", "@efg-hermes.com; quoted", "efghldg.com", DV),
    "dubai national insurence": ("B", "", "Unknown", "Banking / Finance / Insurance", "Local established", "@dni.ae; DFM-listed insurer; in progress", "dni.ae", DV),
    "finance house": ("B", "", "Unknown", "Banking / Finance / Insurance", "Local established", "ADX-listed finance company", "financehouse.ae", DV),
    "liva insurance": ("B", "LIVA Group", "Confirmed", "Banking / Finance / Insurance", "Regional", "", "livainsurance.com", DV),
    "phillipcapital difc private": ("B", "PhillipCapital", "Confirmed", "Banking / Finance / Insurance", "Multinational", "", "phillipcapital.com", DV),
    "pacific prime": ("B", "Pacific Prime", "Confirmed", "Banking / Finance / Insurance", "Multinational", "@pacificprime.com; marked Decent Name", "pacificprime.com", DV),
    "plus500": ("B", "Plus500", "Confirmed", "Banking / Finance / Insurance", "Multinational", "LSE-listed; order won", "plus500.com", DV),
    "multiply": ("A", "Multiply Group (IHC)", "Confirmed", "Other / Conglomerate", "Major UAE brand", "@multiply.ae; ADX-listed IHC holding", "multiply.ae", DV),
    "paymentology": ("B", "", "Unknown", "Technology", "Multinational", "Global card-issuing processor; order won", "paymentology.com", DV),
    "alaan": ("C", "", "Unknown", "Technology", "Growth startup", "Marked BIG Name - UAE fintech start-up (VC backed), not major corporate", "alaanpay.com", DV),
    # ---------------- Retail / luxury / F&B ----------------
    "landmark": ("A", "Landmark Group", "Confirmed", "Retail / Consumer / Luxury", "Major UAE brand", "Major Dubai retail conglomerate", "landmarkgroup.com", DV),
    "landmark group styli": ("A", "Landmark Group", "Confirmed", "Retail / Consumer / Luxury", "Major UAE brand", "@landmarkgroup.com; order won", "landmarkgroup.com", DV),
    "majid al futtaim": ("A", "Majid Al Futtaim", "Confirmed", "Retail / Consumer / Luxury", "Major UAE brand", "2 enquiries", "majidalfuttaim.com", DV),
    "majid al futaim": ("A", "Majid Al Futtaim", "Confirmed", "Retail / Consumer / Luxury", "Major UAE brand", "", "majidalfuttaim.com", DV),
    "agthia": ("A", "Agthia Group (ADQ)", "Confirmed", "Food & Beverage", "Major UAE brand", "@agthia.com; ADX-listed; order won", "agthia.com", DV),
    "foodco": ("B", "Foodco National Foodstuff", "Confirmed", "Food & Beverage", "Local established", "ADX-listed food group", "foodco.ae", DV),
    "al islami foods": ("B", "", "Unknown", "Food & Beverage", "Local established", "Major UAE halal food brand; order won", "alislami.ae", DV),
    "nesto marketing": ("B", "Nesto Group", "Confirmed", "Retail / Consumer / Luxury", "Regional", "GCC hypermarket chain", "nestogroup.com", DV),
    "girardperregaux": ("B", "Sowind Group", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "Swiss luxury watchmaker", "girard-perregaux.com", DV),
    "roberto coin": ("B", "Roberto Coin", "Confirmed", "Retail / Consumer / Luxury", "Multinational", "Italian luxury jeweller", "robertocoin.com", DV),
    "kayali": ("B", "Kayali", "Confirmed", "Retail / Consumer / Luxury", "Major UAE brand", "Dubai-born fragrance brand; 2 won orders", "kayali.com", DV),
    "afnan perfumes": ("B", "Afnan", "Confirmed", "Retail / Consumer / Luxury", "Local established", "Major UAE perfume house", "afnan.com", DV),
    "jamjoom fashion": ("B", "Jamjoom Group", "Probable", "Retail / Consumer / Luxury", "Regional", "Saudi fashion retailer", "", DV),
    "eyewa": ("B", "", "Unknown", "Retail / Consumer / Luxury", "Regional", "Large GCC eyewear retailer", "eyewa.com", DV),
    "kaya clinic": ("B", "Kaya Ltd", "Confirmed", "Healthcare", "Regional", "Skin clinic chain", "kayaclinic.com", DV),
    "dubai gold and jewellery": ("B", "", "Unknown", "Associations / Non-profit", "Trade body", "Dubai Gold & Jewellery Group trade association", "", DV),
    "eurocoffee lavazza": ("C", "Lavazza (distributor)", "Probable", "Food & Beverage", "Distributor", "Marked Big Name - it is the local Lavazza distributor, not Lavazza itself", "", DV),
    "dr scent": ("C", "", "Unknown", "Retail / Consumer / Luxury", "Local established", "Marked Big Name - UAE fragrance retailer, mid-size", "", NV),
    "almosafer": ("B", "Seera Group", "Confirmed", "Tourism", "Regional", "Saudi travel platform", "almosafer.com", DV),
    "cruise saudi": ("A", "Public Investment Fund (KSA)", "Confirmed", "Tourism", "Semi-Government", "PIF-owned cruise company", "cruisesaudi.com", DV),
    # ---------------- Tech ----------------
    "datarobot": ("B", "DataRobot", "Confirmed", "Technology", "Multinational", "@datarobot.com", "datarobot.com", DV),
    "crayon": ("B", "Crayon Group", "Confirmed", "Technology", "Multinational", "@crayon.com", "crayon.com", DV),
    "outsystems": ("B", "OutSystems", "Confirmed", "Technology", "Multinational", "", "outsystems.com", DV),
    "odoo": ("B", "Odoo", "Confirmed", "Technology", "Multinational", "@odoo.com", "odoo.com", DV),
    "bmc software": ("B", "BMC", "Confirmed", "Technology", "Multinational", "", "bmc.com", DV),
    "nagarro mena": ("B", "Nagarro SE", "Confirmed", "Technology", "Multinational", "", "nagarro.com", DV),
    "noventiq seven seas technology": ("B", "Noventiq", "Confirmed", "Technology", "Multinational", "", "noventiq.com", DV),
    "iec telecom": ("B", "IEC Telecom", "Confirmed", "Technology", "Regional", "In progress", "iec-telecom.com", DV),
    "moglix": ("B", "Moglix", "Confirmed", "Technology", "Multinational", "", "moglix.com", DV),
    "cntxt ai": ("B", "CNTXT (Aramco-Cognite JV)", "Probable", "Technology", "Regional", "Order won", "cntxt.com", DV),
    "cars24": ("B", "CARS24", "Confirmed", "Automotive", "Multinational", "Marked big name", "cars24.ae", DV),
    "yalla technology fzllc": ("B", "Yalla Group (NYSE)", "Probable", "Technology", "Multinational", "Order won (crystal chess)", "yalla.com", DV),
    "yas holding technology abu": ("B", "Yas Holding", "Probable", "Other / Conglomerate", "Major local group", "Abu Dhabi holding group", "", NV),
    "khaleej times": ("B", "Galadari group", "Confirmed", "Media", "Major UAE brand", "Leading UAE daily; 2 enquiries", "khaleejtimes.com", DV),
    "arn": ("B", "Dubai Media Inc. (probable - Arabian Radio Network)", "Probable", "Media", "Semi-Government", "", "arn.ae", NV),
    # ---------------- Health / education ----------------
    "skmc sheikh khalifa hospital": ("A", "SEHA / PureHealth", "Confirmed", "Healthcare", "Semi-Government", "Sheikh Khalifa Medical City Abu Dhabi", "seha.ae", DV),
    "m42": ("A", "M42 (Mubadala / G42)", "Confirmed", "Healthcare", "Semi-Government", "Abu Dhabi health-tech group", "m42.ae", DV),
    "zulekha hospital": ("B", "Zulekha Healthcare Group", "Confirmed", "Healthcare", "Local established", "", "zulekhahospitals.com", DV),
    "ahalia medical": ("B", "Ahalia Group", "Confirmed", "Healthcare", "Local established", "", "ahalia.ae", DV),
    "sheikh sultan bin zayed hospital": ("B", "", "Unknown", "Healthcare", "Government", "Hospital - confirm operator", "", NV),
    "nyu abu dhabi": ("A", "New York University", "Confirmed", "Education", "Multinational", "@nyu.edu", "nyuad.nyu.edu", DV),
    "mbzuai library": ("A", "Government of Abu Dhabi", "Confirmed", "Education", "Government", "Mohamed bin Zayed University of AI", "mbzuai.ac.ae", DV),
    "abu dhabi university": ("B", "", "Unknown", "Education", "Local established", "", "adu.ac.ae", DV),
    "ajman university": ("B", "", "Unknown", "Education", "Local established", "", "ajman.ac.ae", DV),
    "university of birmingham": ("B", "University of Birmingham", "Confirmed", "Education", "Multinational", "Dubai campus", "birmingham.ac.uk/dubai", DV),
    "university of technology and applied sciences utas suhar": ("B", "Government of Oman", "Confirmed", "Education", "Government", "Oman state university; order won", "utas.edu.om", DV),
    "essec business school": ("B", "ESSEC", "Confirmed", "Education", "Multinational", "@essec.edu", "essec.edu", DV),
    "brighton college school": ("B", "Brighton College", "Probable", "Education", "Multinational", "Premium international school brand", "", DV),
    "sabis": ("B", "SABIS", "Confirmed", "Education", "Multinational", "@sabis.net; school network; 3 enquiries", "sabis.net", DV),
    "sabis school": ("B", "SABIS", "Confirmed", "Education", "Multinational", "School network", "sabis.net", DV),
    "adnocschool": ("B", "ADNOC", "Probable", "Education", "Semi-Government", "ADNOC Schools network", "adnocschools.ae", DV),
    "kumon": ("B", "Kumon Institute", "Confirmed", "Education", "Multinational", "@kumon.ae", "kumon.ae", DV),
    "emirates literature foundation": ("B", "", "Unknown", "Associations / Non-profit", "Non-profit", "Runs Emirates Airline Festival of Literature", "elf.ae", DV),
    "emirates film festival": ("C", "", "Unknown", "Media", "Event organiser", "@emiratesfilmfest.com", "", NV),
    # ---------------- Sports ----------------
    "international cricket council": ("A", "ICC", "Confirmed", "Sports", "International body", "Global cricket governing body HQ Dubai; in progress", "icc-cricket.com", DV),
    "al wasal sc": ("B", "Government of Dubai-affiliated club", "Probable", "Sports", "Semi-Government", "@alwaslsc.ae; medals quotation", "alwaslsc.ae", DV),
    "al ahli club": ("B", "", "Unknown", "Sports", "Semi-Government", "Major UAE sports club", "", DV),
    "special olympics uae": ("B", "Special Olympics", "Confirmed", "Sports", "Non-profit", "Enquiry marked 'not our scope'", "specialolympicsuae.org", DV),
    "uae badminton federation": ("B", "UAE Government sports federation", "Confirmed", "Sports", "Semi-Government", "", "", DV),
    "uae shooting federation": ("B", "UAE Government sports federation", "Confirmed", "Sports", "Semi-Government", "", "", DV),
    "saudi cricket": ("B", "Saudi Arabian Cricket Federation", "Probable", "Sports", "Semi-Government", "Won - looking for trophy supplier", "", DV),
    "saudi automobile and motorcycle": ("B", "Saudi Automobile & Motorcycle Federation", "Probable", "Sports", "Semi-Government", "", "samf.sa", DV),
    "e1 series": ("B", "E1 Series (PIF-backed)", "Confirmed", "Sports", "Multinational", "@e1series.com; electric powerboat championship", "e1series.com", DV),
    "palm tee challenge": ("C", "", "Unknown", "Sports", "Event organiser", "Marked Big name, gmail contact - golf event; order won", "", NV),
    # ---------------- Agencies / resellers flagged BIG in source ----------------
    "besaux premium merchandising services": ("C", "", "Unknown", "Gifting / Promotional Reseller", "Trade buyer", "Marked BIG NAME - web shows it is a Dubai corporate-gifting house (a reseller), not a major corporate", "besaux.com", WV),
    "besaux premium merchandising service": ("C", "", "Unknown", "Gifting / Promotional Reseller", "Trade buyer", "Same as Besaux", "besaux.com", WV),
    "besaux": ("C", "", "Unknown", "Gifting / Promotional Reseller", "Trade buyer", "Same as Besaux", "besaux.com", WV),
    "social kapita": ("C", "", "Unknown", "Advertising / Marketing", "Trade buyer", "Marked Big name - boutique digital marketing agency", "socialkapita.com", WV),
    "orion events managements": ("C", "", "Unknown", "Events & Exhibitions", "Trade buyer", "Marked BIG NAME - several Dubai 'Orion' event firms exist; no evidence of major scale", "", WV),
    "vision events": ("C", "", "Unknown", "Events & Exhibitions", "Trade buyer", "Marked Big Name - 3 won orders (valuable repeat buyer) but company scale not publicly evidenced", "", WV),
    "papaya print media": ("C", "Papaya Communications Group", "Probable", "Advertising / Marketing", "Trade buyer", "Marked Big name - print/media agency", "papayacommunicationsgroup.com", DV),
    "icon marcom": ("C", "", "Unknown", "Advertising / Marketing", "Trade buyer", "Marked Big Name - marketing agency (2 entries)", "", NV),
    "quill communications events manager": ("C", "", "Unknown", "Events & Exhibitions", "Trade buyer", "Marked Big Name - events agency", "", NV),
    "itc promotions kuwait": ("C", "", "Unknown", "Advertising / Marketing", "Trade buyer", "Marked Big name - promotions agency", "", NV),
    "we do advertising": ("D", "", "Unknown", "Advertising / Marketing", "Trade buyer", "Marked BIG NAME - no evidence of scale", "", NV),
    "lucid media": ("E", "", "Unknown", "Advertising / Marketing", "Trade buyer", "Marked Big name - not evidenced; quoted", "", NV),
    "active media": ("E", "", "Unknown", "Advertising / Marketing", "Trade buyer", "Marked Big name - not evidenced; order won", "", NV),
    "oumolat security printing": ("C", "", "Unknown", "Manufacturing / Industrial", "Local established", "@oumolat.com; marked BIG NAME - security printer, mid-size", "oumolat.com", DV),
    "aramtec": ("C", "", "Unknown", "Technology", "Local established", "Marked Big name - AV/tech distributor, mid-size", "", NV),
    "ark ventures": ("E", "", "Unknown", "Other", "Unclear", "Marked Big name - no evidence", "", NV),
    "auditoire ksa": ("C", "Auditoire (Havas Events)", "Probable", "Events & Exhibitions", "Trade buyer", "Marked BIG NAME - KSA arm of French events agency", "auditoire.com", DV),
    "elite property dxb": ("D", "", "Unknown", "Real Estate", "Small brokerage", "Marked BIG NAME - brokerage, no evidence of scale", "", NV),
    "gulf land property": ("E", "", "Unknown", "Real Estate", "Unclear", "Marked BIG NAME - no evidence; no requirement recorded", "", NV),
    "silver yachts and repair": ("D", "", "Unknown", "Other", "Small business", "Marked BIG NAME - repair enquiry", "", NV),
    "super yacht interiors": ("C", "", "Unknown", "Manufacturing / Industrial", "Local established", "Marked BIG NAME - fit-out company; catalogue request", "superyachtinteriors.com", NV),
    "aeroficial intelligence gmbh": ("D", "", "Unknown", "Technology", "Small business", "Marked BIG NAME - small German start-up", "aeroficial.com", NV),
    "mohammed albarwani": ("E", "Possibly MB Holding (Oman)", "Unconfirmed", "Other", "Unclear", "Marked BIG NAME - individual's name only", "", NV),
    "gulf craft": ("B", "Gulf Craft", "Confirmed", "Manufacturing / Industrial", "Local established", "Major UAE yacht builder", "gulfcraftinc.com", DV),
    "gulfcraft": ("B", "Gulf Craft", "Confirmed", "Manufacturing / Industrial", "Local established", "Major UAE yacht builder", "gulfcraftinc.com", DV),
    "julfar": ("B", "Gulf Pharmaceutical Industries (Julphar)", "Probable", "Healthcare", "Local established", "RAK pharma manufacturer", "julphar.net", DV),
    "al rostamani": ("B", "Al Rostamani Group", "Probable", "Other / Conglomerate", "Major local group", "Order won", "alrostamanigroup.ae", DV),
    "al fardan": ("B", "Al Fardan Group", "Confirmed", "Other / Conglomerate", "Major local group", "", "alfardan.com", DV),
    "al shirawi": ("B", "Al Shirawi Group", "Confirmed", "Other / Conglomerate", "Major local group", "", "alshirawi.com", DV),
    "dulsco": ("B", "Dulsco", "Confirmed", "Professional Services", "Major local group", "", "dulsco.com", DV),
    "danube": ("B", "Danube Group", "Confirmed", "Real Estate", "Major local group", "", "", DV),
    "rose trading supplies a subsidiary of al rajhi": ("B", "Al Rajhi (group to confirm)", "Unconfirmed", "Other / Conglomerate", "Regional", "Says subsidiary of Al Rajhi; quoted gold-plated armour", "", NV),
    "tamimi consulting": ("E", "Possibly Al Tamimi & Co", "Unconfirmed", "Professional Services", "Unclear", "", "", NV),
    "uitp": ("B", "UITP", "Confirmed", "Associations / Non-profit", "International body", "International public transport association", "uitp.org", DV),
    "undp icpsd": ("A", "United Nations Development Programme", "Confirmed", "Associations / Non-profit", "International body", "@undp.org", "undp.org", DV),
    "cii the confederation of indian industry": ("B", "CII", "Confirmed", "Associations / Non-profit", "International body", "@cii.in", "cii.in", DV),
    "aicpaandcima": ("B", "AICPA & CIMA", "Confirmed", "Associations / Non-profit", "International body", "", "aicpa-cima.com", DV),
    "cci france": ("C", "", "Unknown", "Associations / Non-profit", "Chamber", "@ccifranceuae.com", "ccifranceuae.com", DV),
    "ah": ("E", "", "Unknown", "Other", "Unclear", "Recorded only as 'AH' - 3 won orders (crystal models); identify the company", "", NV),
}

# spelling / legal-name variants that should resolve to one KB key
ALIASES = {
    "frago men": "fragomen",
    "majid al futaim": "majid al futtaim",
    "azizi developments": "azizi development",
    "gulfcraft": "gulf craft",
    "general electric vernova": "ge vernova",
    "besaux premium merchandising services": "besaux",
    "besaux premium merchandising service": "besaux",
    "sabis school": "sabis",
    "jcb construction equipment": "jcb",
    "designsmith": "design smith",
    "unitedtm": "united trademark and patent services",
    "serindipity events in": "serindipity events",
    "homporium arrange adv": "homporium arrange advertising",
    "hummingbird advertising": "hummingbird advertising",
    "ekaga": "ekaga",
    "aandm events": "aandm events",
    "a and m events": "aandm events",
    "arabland solutions": "arab land",
    "arab land advertising": "arab land",
    "signworks fz": "sign works",
    "signworks": "sign works",
    "starboard designs": "starboard design",
    "loyal brothers": "loyal brothers",
    "vision perfume": "vision perfume",
    "adorn advertisement design and printing": "adorn advertisement",
    "nobles printing": "noble printing",
    "luna pr": "luna pr",
    "the luxury advertising abu dhabi": "the luxury advertising",
    "lincon university": "lincoln university of business and management lubm",
    "emirates palace": "emirates palace",
    "auditoire": "auditoire ksa",
    "aeroficial intelligence": "aeroficial intelligence gmbh",
    "special olympics": "special olympics uae",
    "trans guard": "transguard",
    "aicpa and cima": "aicpaandcima",
    "knowledge fund gov": "knowledge fund establishment gov",
    "odoo dwc": "odoo",
    "philippine consulate": "philippine consulate general",
    "yas holding technology abu dhabi": "yas holding technology abu",
    "yalla technology": "yalla technology fzllc",
    "linesight dmcc": "linesight",
}
